services:
  - type: web
    name: astrology-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run_production.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
